version: '3.7'

services:
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile.postgres
    image: koders-postgres:local
    container_name: koders-postgres
    ports:
    - '5432:5432'
    environment:
    - POSTGRES_PASSWORD=kodersadmin